server:
  port: 8083
  error:
    include-message: always
spring:
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
        classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://ec2-52-54-212-232.compute-1.amazonaws.com:5432/dc80cv5f3r4ok8?socketTimeout=3
    username: gekeojkbsmezrk
    password: 966d6028a05a0998ad7d771380c478c413978936380c5d3c83a518d73cdd438f
    driverClassName: org.postgresql.Driver
